server:
  port: 8100

eureka: #将该服务（配置中心服务端）注册到注册中心
  instance:
    hostname: discovery
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

spring:
  application:
    name: config
  cloud:
    config:
      server: #声明该服务是配置中心的服务端
        git:
          uri: https://github.com/maxwellyue/spring-cloud-sample
          search-paths: config-repo
          username: maxwellyue
          password: loveyan0906

