server:
  port: 8040

logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error
  path: /Users/yue/Downloads/


turbine:
  stream:
    port: 8041

eureka:
  instance:
    hostname: discovery
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

spring:
  application:
      name: monitor
  rabbitmq:
    host: rabbitmq
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://monitor:${turbine.stream.port}
security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}

management:
  security:
    enabled: false
endpoints:
  health:
    enabled: true
    sensitive: false
  actuator:
    enabled: true
    sensitive: false
