server:
  port: 8040

logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error

turbine:
  stream:
    port: 8041

eureka:
  instance:
    hostname: discovery
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

spring:
  application:
      name: monitor
  rabbitmq:
    host: rabbitmq
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://monitor:${turbine.stream.port}